### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by YongZh958** [ZYN-1101/DandR#3]
Traceback (most recent call last):
  File "tools/extract_results.py", line 59, in <module>
    main()
  File "tools/extract_results.py", line 34, in main
    results.append([fid] + [float(x) for x in res_info.split(':')[-1].split(',')])
  File "tools/extract_results.py", line 34, in <listcomp>
    results.append([fid] + [float(x) for x in res_info.split(':')[-1].split(',')])
ValueError: could not convert string to float: ' Evaluating voc_2007_test_all1 using 2007 metric. Note that results do not use the official Matlab API.'

**Comment by ZYN-1101** [comment]
The script automatically gets the test results from the log file's last line. Please double-check whether there is an error in the testing process causing no test results in the log file to resolve this issue.
